controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Employee;
use yii\data\ActiveDataProvider;
use app\models\Product;
use app\models\Basketitem;
use app\models\Basket;

class AdminController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Employee::findBySql('SELECT * FROM employee'),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        //SELECT * FROM `employee` LIMIT 10
        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionEmployee($id = null) {
        $model = new Employee();
        if ($id && $find = Employee::findBySql("SELECT * FROM employee WHERE id = $id LIMIT 1")) { //SELET * FROM employee WHERE id=1 LIMIT 1
            $model = $find;
            if (Yii::$app->request->get('delete')) {
                if ($model->delete()) { //DELETE FROM employee WHERE id = 1;
                    Yii::$app->session->setFlash('employeeSubmitted');
                    return $this->redirect(['admin/index']);
                }
            }
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('employeeSubmitted');
            return $this->redirect(['admin/index']);
        }
        return $this->render('_employee', [
                    'model' => $model,
        ]);
    }

    public function actionOverview() {
        $stats = [];
        $connection = Yii::$app->getDb();
        $command = $connection->createCommand('SELECT COUNT(*) FROM product');
        $numberOfProducts = $command->queryScalar();
        
        $orderItems = Basketitem::findBySql("SELECT * FROM `basketitem`")->all(); //SELECT * FROM `basketitem`
        $sum = 0;
        foreach ($orderItems as $item) {
            $sum += $item->quantity;
        }
        $numberOfOrders = $sum;
        $stats['numberOfProducts'] = $numberOfProducts;
        $stats['numberOfOrders'] = $numberOfOrders;
        return $this->render('overview', ['stats' => $stats]);
    }

    public function actionSales() {
        $fromdate = !empty(Yii::$app->request->get('from_date')) ? strtotime(Yii::$app->request->get('from_date')) : time();
        $todate = !empty(Yii::$app->request->get('to_date')) ? strtotime(Yii::$app->request->get('to_date')) : time();
        $todateUsed = strtotime('+1 day', $todate);
        $stats = [];
         //SELECT * FROM `basket` WHERE (updated_at>=1464127200) AND (updated_at<=1464213600)
        $baskets = Basket::findBySql('SELECT * FROM basket WHERE (updated_at>='. $fromdate.') AND (updated_at<='. $todateUsed.')')->all();
        $orderCount = count($baskets);
        $numberOfProductsSold = 0;
        $totalPrice = 0;
        $profit = 0;
        $tax = 0;
        foreach ($baskets as $basket) {
            $numberOfProductsSold = $basket->itemcount;
            $profit += $basket->profit;
            $totalPrice += $basket->totalcost;
            $tax += $basket->tax;
        }

        $stats = [
            'orders' => $orderCount,
            'products' => $numberOfProductsSold,
            'price' => $totalPrice,
            'profit' => $profit,
            'tax' => $tax,
        ];
        return $this->render('sales', ['stats' => $stats, 'baskets' => $baskets, 'from_date' => $fromdate, 'to_date' => $todate]);
    }

}

controllers/CustomerController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Product;
use yii\data\ActiveDataProvider;
use app\models\Basketitem;
use app\models\Basket;

class CustomerController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::findBySql("SELECT * FROM product"),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionProduct($id = null) {
        $model = new Basketitem();
        if ($id && $find = Product::findBySql('SELECT * FROM product WHERE id = '.$id.' LIMIT 1')->one()) { //SELECT * FROM product WHERE id = $id LIMIT 1
            $product = $find;
        } else {
            Yii::$app->session->setFlash('Error');
            return $this->redirect(['customer/index']);
        }
        $model->product_id = $product->id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) { // INSERT query
            Yii::$app->session->setFlash('Submitted');
            return $this->redirect(['customer/index']);
        }
        $product->customerprice = Yii::$app->formatter->asCurrency($product->customerprice);
        return $this->render('_product', [
                    'model' => $model,
                    'product' => $product,
        ]);
    }

    public function actionBasket() {
        if (!$basket = Yii::$app->user->identity->hasActiveBasket()) {
            return $this->redirect(['customer/index']);
        }
        return $this->render('basket', ['basket' => $basket]);
    }

    public function actionCheckout() {
        if (!$basket = Yii::$app->user->identity->hasActiveBasket()) {
            return $this->redirect(['customer/index']);
        }
        $basket->totalcost = $basket->totalPrice();
        $basket->status = Basket::STATUS_COMPLETE;
        $basket->save();
        Yii::$app->session->setFlash('Checkout');
        return $this->redirect(['customer/index']);
    }

}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <script>
            var BASE_URL = '<?= Url::base(true); ?>';
        </script>
    </head>
    <body>
        <?php $this->beginBody() ?>


        <nav class="teal">
            <div class="nav-wrapper container">
                <a href="<?= Url::toRoute(['/site/index']); ?>" class="brand-logo">BAU Supermarket</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="<?= Url::toRoute(['/site/index']); ?>">Home</a></li>
                    <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) { ?>
                        <li><a href="<?= Url::toRoute(['/admin/overview']); ?>">Overview</a></li>
                        <li><a href="<?= Url::toRoute(['/admin/sales']); ?>">Sales</a></li>
                    <?php } ?>
                    <?php if (Yii::$app->user->isGuest) { ?>
                        <li><a href="<?= Url::toRoute(['/site/login']); ?>">Login</a></li>
                    <?php } else { ?>
                        <li><a href="<?= Url::toRoute(['/site/logout']); ?>">logout</a></li>
                    <?php } ?>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="<?= Url::toRoute(['/site/index']); ?>">Home</a></li>
                    <?php if (Yii::$app->user->isGuest) { ?>
                        <li><a href="<?= Url::toRoute(['/site/login']); ?>">Login</a></li>
                    <?php } else { ?>
                        <li><a href="<?= Url::toRoute(['/site/logout']); ?>">logout</a></li>
                    <?php } ?>
                </ul>
            </div>
        </nav>
        <main>
            <div class="container">
                <?= $content ?>
                <?php if (!Yii::$app->user->isGuest && Yii::$app->user->identity->hasActiveBasket()) { ?>
                    <div class="fixed-action-btn" style="top: 20px; right: 104px;">
                        <?= Html::a('<i class="large material-icons">shopping_cart</i>', ['/customer/basket'], ['class' => 'btn-floating btn-large teal lighten-2']); ?>

                    </div>
                    <?php
                }
                ?>
            </div>
        </main>

        <footer class="page-footer teal">
            <div class="footer-copyright teal">
                <div class="container">
                    © <?= date('Y') ?> BAU Supermarket
                    <span class="grey-text text-lighten-4 right">Created by Rawad Salhab</span>
                </div>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>