controllers/CustomerController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Product;
use yii\data\ActiveDataProvider;
use app\models\Basketitem;
use app\models\Basket;

class CustomerController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Product::findBySql("SELECT * FROM product"),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionProduct($id = null) {
        $model = new Basketitem();
        if ($id && $find = Product::findBySql('SELECT * FROM product WHERE id = '.$id.' LIMIT 1')->one()) { //SELECT * FROM product WHERE id = $id LIMIT 1
            $product = $find;
        } else {
            Yii::$app->session->setFlash('Error');
            return $this->redirect(['customer/index']);
        }
        $model->product_id = $product->id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) { // INSERT query
            Yii::$app->session->setFlash('Submitted');
            return $this->redirect(['customer/index']);
        }
        $product->customerprice = Yii::$app->formatter->asCurrency($product->customerprice);
        return $this->render('_product', [
                    'model' => $model,
                    'product' => $product,
        ]);
    }

    public function actionBasket() {
        if (!$basket = Yii::$app->user->identity->hasActiveBasket()) {
            return $this->redirect(['customer/index']);
        }
        return $this->render('basket', ['basket' => $basket]);
    }

    public function actionCheckout() {
        if (!$basket = Yii::$app->user->identity->hasActiveBasket()) {
            return $this->redirect(['customer/index']);
        }
        $basket->totalcost = $basket->totalPrice();
        $basket->status = Basket::STATUS_COMPLETE;
        $basket->save();
        Yii::$app->session->setFlash('Checkout');
        return $this->redirect(['customer/index']);
    }

}

views/customer/_product.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Pricing;

$this->title = 'Add To Basket';
?>
<h4 class="center teal-text">Buy Product</h4>
<div class="card-panel white">
    <div class="card-content">
        <?php
        $form = ActiveForm::begin([
                    'id' => 'add-to-basket-form',
        ]);
        ?>
        <?= $form->field($product, 'title')->textInput(['disabled' => 'disabled']); ?>
        <?= $form->field($product, 'customerprice')->textInput(['disabled' => 'disabled']); ?>
        <?= $form->field($model, 'quantity'); ?>

        <div class="center">
            <?= Html::submitButton('Add to basket', ['class' => 'waves-effect waves-light btn']) ?>
        </div>

        <?php ActiveForm ::end(); ?>
    </div>
</div>

views/customer/basket.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

$this->title = 'My Basket';
?>
<h4 class="center teal-text">My Basket</h4>
<div class="card-panel white">
    <div class="card-content">
        <table class="responsive-table highlight">
            <thead>
                <tr>
                    <th data-field="id">Item Name</th>
                    <th data-field="name">Quantity</th>
                    <th data-field="price">Price</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($basket->basketitems as $item) { ?>
                    <tr>
                        <td><?= $item->product->title ?></td>
                        <td><?= $item->quantity ?></td>
                        <td><?= Yii::$app->formatter->asCurrency($item->price) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th data-field="totalprice"><?= Yii::$app->formatter->asCurrency($basket->totalPrice()) ?></th>
                </tr>
            </tfoot>
        </table>
        <div class="center">
            <?= Html::a('<i class="material-icons left">payment</i> Checkout', ['/customer/checkout'], ['class' => 'waves-effect waves-light btn']) ?>
        </div>
    </div>
</div>

views/customer/index.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

$this->title = 'Buy Products';
?>
<?php if (Yii::$app->session->hasFlash('Submitted')) { ?>
    <div class="card-panel green">
        <span class="white-text">
            Product added to basket!
        </span>
    </div>
<?php } ?>
<?php if (Yii::$app->session->hasFlash('Error')) { ?>
    <div class="card-panel red">
        <span class="white-text">
            Error no product!
        </span>
    </div>
<?php } ?>
<?php if (Yii::$app->session->hasFlash('Checkout')) { ?>
    <div class="card-panel green">
        <span class="white-text">
            Order Completed Successfully!
        </span>
    </div>
<?php } ?>
<h4 class="center teal-text">Product List</h4>
<div class="card-panel white">
    <div class="card-content">
        <?php
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'tableOptions' => ['class' => 'highlight centered responsive-table', 'id' => 'product-list'],
            'columns' => [
                'id',
                'title',
                [
                    'attribute' => 'customerprice',
                    'format' => 'Currency',
                ],
                [
                    'attribute' => 'expiry_date',
                    'format' => ['date', 'php:Y-m-d']
                ],
            ],
        ]);
        ?>
    </div>
</div>